---
- name: 
  delegate_to: localhost
  command: id -un
  register: local_user
  check_mode: no

- block: 
  - name: "Log the run of this role"
    script: files/c_logger {{ local_user.stdout }} {{ pool_home_dir }}/log/ansible

  - name: "Create pool creation script"
    template:
         src: "create_pools.j2"
         dest: "{{ pool_home_dir }}/create_pools"
         mode: 0755 

  - name: "Create pools"
    command: "{{ pool_home_dir }}/create_pools"
    notify:
         - "redo layouts template"
         - "restart_dcache"

  remote_user: "{{ pool_remote_user }}"
